apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: tirocinio
  description: Gruppo del tirocinio
  links:
    - url: https://github.com/Furini00/backstage-catalog-tirocinio
      title: Repository GitHub del Tirocinio
      icon: github
spec:
  type: team
  profile:
    displayName: Gruppo del tirocinio
    email: tirocinio@example.com
    picture: https://example.com/groups/tirocinio.jpeg
  parents: sviluppo
  children: [sviluppo]
  members: [furini, professore]
  
---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sviluppo
  description: Gruppo generale di sviluppo
  links:
    - url: https://github.com/Furini00/backstage-catalog-tirocinio
      title: Repository GitHub del Tirocinio
      icon: github
spec:
  type: team
  profile:
    displayName: Gruppo di sviluppo
    email: sviluppo@example.com
  parents: sviluppo
  children: []
  members: [furini]
