apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Tirocinio-Furini
  description: Tirocinio Furini
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: 'Furini00/backstage-catalog-tirocinio'
  links:
    - url: https://github.com/Furini00/backstage-catalog-tirocinio
      title: Repository GitHub del Tirocinio
      icon: github
spec:
  type: service
  lifecycle: production
  owner: furini

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: hello-ts
  description: File TypeScript di test
  annotations:
    github.com/project-slug: 'https://github.com/Furini00/backstage-catalog-tirocinio/blob/main/hello.ts'
spec:
  type: file
  owner: furini
