apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Tirocinio-Furini
  description: Tirocinio Furini
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: 'Furini00/backstage-catalog-tirocinio'
    uptimeMonitorId: '798608258'
  links:
    - url: https://github.com/Furini00/backstage-catalog-tirocinio
      title: Repository GitHub del Tirocinio
      icon: github
spec:
  type: service
  lifecycle: production
  owner: tirocinio

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tirocinio-database
  description: Database per il progetto Tirocinio Furini
  annotations:
    github.com/project-slug: 'Furini00/tirocinio-database'
  links:
  - url: https://github.com/Furini00/backstage-catalog-tirocinio
    title: Repository GitHub del Tirocinio
    icon: github
spec:
  type: database
  lifecycle: production
  owner: tirocinio
  subcomponentOf: Tirocinio-Furini
