apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Tirocinio-Furini
  description: Tirocinio Furini
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: 'Furini00/backstage-catalog-tirocinio'
    uptimeMonitorId: '798608258'
    sonarqube.org/project-key: ltirocinio-furini
  links:
    - url: https://github.com/Furini00/backstage-catalog-tirocinio
      title: Repository GitHub del Tirocinio
      icon: github
spec:
  type: service
  lifecycle: production
  owner: tirocinio

  
