name: CI

# Controls when the workflow will run
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - uses: actions/checkout@v4

      # Setup Node.js e TypeScript
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Usa la versione di Node.js che ti serve

      - name: Install dependencies
        run: |
          npm install -g typescript
          npm install

      # Compilazione del file TypeScript
      - name: Compile TypeScript
        run: tsc helloWorld.ts

      # Esecuzione del file compilato (JavaScript)
      - name: Run compiled JavaScript
        run: node helloWorld.js

      # Messaggio di successo o errore
      - name: Display a message
        run: |
          echo "CI workflow completed!"
