name: CI

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ] 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Check for changes in src
        id: check_src
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^service_with_docs/src/'; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Check TypeScript installation
        if: env.changes == 'true'
        run: npx tsc --version

      - name: Compile TypeScript
        if: env.changes == 'true'
        run: npm run build

      - name: Run tests
        run: npm test
