name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Installazione Node.js e dipendenze
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Assicurati di usare una versione recente

      - name: Install TypeScript
        run: npm install -g typescript

      # Step 3: Creazione di un file TS di test (opzionale, se non lo aggiungi manualmente)
      - name: Create a sample TypeScript file
        run: echo 'console.log("Hello, GitHub Actions!");' > hello.ts

      # Step 4: Compilazione del file TypeScript
      - name: Compile TypeScript
        run: tsc hello.ts

      # Step 5: Esegui il file compilato con Node.js
      - name: Run JavaScript output
        run: node hello.js
