name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout del repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Assicurati di fare il checkout completo del repository

      # Step 2: Verifica la struttura delle cartelle
      - name: List files in the repository
        run: |
          echo "Listing files in the repository"
          ls -R  # Elenco ricorsivo dei file per vedere la struttura delle cartelle

      # Step 3: Installazione dipendenze e TypeScript
      - name: Install dependencies and TypeScript
        run: |
          cd service_with_docs || exit 1  # Usa il nome corretto della cartella
          npm install
          npm install -g typescript

      # Step 4: Costruzione della documentazione TechDocs
      - name: Build TechDocs
        run: |
          cd service_with_docs  # Usa il nome corretto della cartella
          backstage-cli techdocs:build

      # Step 5: Compilazione TypeScript
      - name: Compile TypeScript
        run: |
          tsc helloWorld.ts
          node helloWorld.js

      # Step 6: Messaggio di completamento
      - name: Display a message
        run: echo "CI workflow completed!"
